version: "3.8"

services:
  res_db:
    image: mysql:latest
    container_name: res_db
    restart: always
    networks:
      - hdv_network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_RANDOM_ROOT_PASSWORD: false
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1
      MYSQL_DATABASE: db_res
    # ports:
    #   - "3306:3306"
    volumes:
      - res-mysql-data:/var/lib/mysql

  res_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: res_service
    depends_on:
      - res_db
    ports:
      - "3001:3001"
    networks:
      - hdv_network
    environment:
      IP: res_service
      PORT: 3001
      DB_IP: res_db
      DB_PORT: 3306
      DB_DIALECT: mysql
      DB_NAME: db_res
      DB_USER: sa
      DB_PASS: 1
      DB_GEN: 1

networks:
  hdv_network:
    driver: bridge
volumes:
  res-mysql-data:
